labels:
  app: vsaq
  team: security
  language: js

stages:
  format:
    image: docker run -i travix/yaml2json
    commands:
    - cat questionnaires/travix_squad_12.yaml | yaml-to-json

  build:
    image: travix/vsaq
    shell: /bin/bash
    commands:
    - bash do.sh build_prod

  deploy:
    image: extensions/gcs
    credentials: gke-development
    action: copy
    source: 'build/*'
    bucket: estafette.secret(q3Jlju-a4DzA-I6L.mMOZDz8bya17YKeiq_Bj63kM7bc00P8GhWCs3IisKw==.idmMFmQNla9iZPDYuv546YmJAHwsRSjKDSruPR6L32QkJ45g9L1RQRN9Q-BAMr3wG4ve-A==)