labels:
  app: vsaq
  team: security
  language: js

stages:
  format:
    image: travix/yaml2json
    commands:
    - ls questionnaires/
    - cat questionnaires/travix_1.yaml | /yaml-to-json
    - for yaml in questionnaires/*.yaml; do cat $yaml | /yaml-to-json > questionnaires/$yaml.json; done
    - ls questionnaires/

  build:
    image: travix/vsaq
    shell: /bin/bash
    commands:
    - mv /vsaq/* .
    - bash do.sh build_prod

  deploy:
    image: extensions/gcs
    credentials: gke-development
    action: copy
    source: 'build/*'
    bucket: estafette.secret(q3Jlju-a4DzA-I6L.mMOZDz8bya17YKeiq_Bj63kM7bc00P8GhWCs3IisKw==.idmMFmQNla9iZPDYuv546YmJAHwsRSjKDSruPR6L32QkJ45g9L1RQRN9Q-BAMr3wG4ve-A==)